# Form implementation generated from reading ui file 'ui/customPlot.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget
from PyQt6.QtWebEngineWidgets import QWebEngineView

class CPlot_Frame(QWidget, object):
    def __init__(self, hlist=None):
        super().__init__()
        self.setupUi(self)

        if hlist:
            self.comboBox.addItems(hlist)
            self.comboBox_2.addItems(hlist)
        
        self.webviewCustom = QWebEngineView()
        self.verticalLayout_2.addWidget(self.webviewCustom)

    def close_window(self):
        self.close()

    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1591, 643)
        # Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        # Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1461, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(50, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.closeCustom = QtWidgets.QToolButton(parent=self.verticalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/icons/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeCustom.setIcon(icon)
        self.closeCustom.setObjectName("closeCustom")
        self.horizontalLayout.addWidget(self.closeCustom)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.verticalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollGraphWidg = QtWidgets.QWidget()
        self.scrollGraphWidg.setGeometry(QtCore.QRect(0, 0, 1455, 501))
        self.scrollGraphWidg.setObjectName("scrollGraphWidg")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.scrollGraphWidg)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 1461, 501))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollGraphWidg)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_3.setText(_translate("Frame", "Parameters"))
        self.label.setText(_translate("Frame", "X-axis:"))
        self.comboBox_2.setItemText(0, _translate("Frame", "-Select-"))
        self.label_2.setText(_translate("Frame", "Y-axis:"))
        self.comboBox.setItemText(0, _translate("Frame", "-Select-"))
        self.closeCustom.setText(_translate("Frame", "..."))
